name: snap-py-simple
summary: A simple hello world
description: |
      Prints Hello world to the screen

version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

# Invoke the command with snap-py-simple
# Invoke the python version with snap-py-simple.python-v
apps:
  snap-py-simple:
    command: bin/myprogram
    plugs: [home, network, network-bind, removable-media]
  python-v:
      command: bin/python3 -V

parts:
  build-the-python-stuff-please:
    plugin: python
    source: .