name: snap-py-simple
summary: A simple hello world
description: |
      Prints Hello world to the screen

#version: git
adopt-info: fred

grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

apps:
  fred:
    command: bin/fred
    plugs: [home, network, network-bind, removable-media]

parts:
  fred:
    plugin: python
    source: .
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(git describe --tags)

