name: building youtube-dl using snapcraft
on:
  push:
    # branches: [ main ]
    tags: ['v*', 'pre*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: Install Git
    #   run: sudo apt-get update && sudo apt-get install -y git
    - name: Set up environment
      run: echo "PATH=$PATH:/usr/bin:/usr/local/bin" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
